const mongoose = require('mongoose');
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '../server/.env') });

const Project = require('../server/src/modules/project/project.model');
const Task = require('../server/src/modules/task/task.model');
const User = require('../server/src/modules/auth/user.model');

// Adjust these numbers for the amount of dummy data you want.
const NUM_PROJECTS = 50;
const TASKS_PER_PROJECT = 200;

async function createDummyData() {
    try {
        console.log('Connecting to MongoDB...');
        await mongoose.connect(process.env.MONGO_URI || 'mongodb://localhost:27017/management-app');

        // Wait for connection to be ready
        if (mongoose.connection.readyState !== 1) {
            await new Promise((resolve, reject) => {
                mongoose.connection.once('open', resolve);
                mongoose.connection.once('error', reject);
                setTimeout(() => reject(new Error('Connection timeout')), 10000);
            });
        }

        console.log('Connected.');

        // Create a single test user (or reuse an existing one)
        let user = await User.findOne({ email: 'dummy@example.com' });
        if (!user) {
            console.log('Creating dummy user...');
            user = await User.create({
                username: 'dummyUser',
                email: 'dummy@example.com',
                password: 'Password123!', // hashed in pre‑save hook
            });
        } else {
            console.log('Using existing dummy user:', user.email);
        }
    } catch (error) {
        console.error('Connection error:', error);
        throw error;
    }

    console.log(`Seeding ${NUM_PROJECTS} projects...`);
    const projects = [];
    for (let i = 0; i < NUM_PROJECTS; i++) {
        const project = await Project.create({
            name: `Dummy Project ${i + 1}`,
            description: 'Generated by seed script',
            owner: user._id,
            members: [{ user: user._id, role: 'Admin' }],
        });
        projects.push(project);
        if ((i + 1) % 10 === 0) process.stdout.write('.');
    }
    console.log('\nProjects created.');

    console.log(`Seeding tasks for each project (${TASKS_PER_PROJECT} tasks/project)...`);
    for (const project of projects) {
        const tasks = [];
        for (let j = 0; j < TASKS_PER_PROJECT; j++) {
            tasks.push({
                title: `Task ${j + 1} for ${project.name}`,
                description: 'Dummy task generated for pagination testing',
                status: ['Todo', 'In Progress', 'Review', 'Completed'][Math.floor(Math.random() * 4)],
                priority: ['Low', 'Medium', 'High', 'Critical'][Math.floor(Math.random() * 4)],
                project: project._id,
                assignees: [],
                createdBy: user._id
            });
        }
        await Task.insertMany(tasks);
        process.stdout.write('.');
    }

    console.log('\nDummy data created successfully');
    await mongoose.disconnect();
}

createDummyData().catch(err => {
    console.error(err);
    process.exit(1);
});
